app/uploadFile/forms.py
from flask import request
from flask_wtf import FlaskForm
from flask_wtf.file import FileField

class UploadFile(FlaskForm):
    file = FileField()
    def getData(self):
        # RETURN THE READ DATA
        pass

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
bootstrap = Bootstrap()

def create_app():
    """Construct the core application."""
    app = Flask(__name__,
                instance_relative_config=True)
    app.config.from_object('config.Config')

    with app.app_context():
        from app.uploadFile import routes as uf_route
        app.register_blueprint(uf_route.uf_bp)
        from app.assets import compile_assets
        compile_assets(app)
        bootstrap.init_app(app)
        return app

app/uploadFile/__init__.py
from flask import Blueprint

uf_bp = Blueprint('uf_bp', __name__,
                    template_folder='templates',
                    static_folder='static')

from app.uploadFile import routes

app/uploadFile/routes.py
from flask import render_template, url_for, redirect, request, send_file
from app.uploadFile import uf_bp
from app.uploadFile.forms import UploadFile
from werkzeug.utils import secure_filename
import os
from runEngine import Engine
engine = Engine()

@uf_bp.route('/', methods=['GET','POST'])
def uploadFile():
    uploadFileForm = UploadFile()
    if uploadFileForm.validate_on_submit():
        print('VALID UPLOAD')
        filename = secure_filename(uploadFileForm.file.data.filename)
        if not os.path.exists('./uploads'):
            os.mkdir('./uploads')
        uploadFileForm.file.data.save('./uploads/' + filename)
        return redirect(url_for('uf_bp.processUpload', secure_filename=filename))
    return render_template('uploadFile.html', uploadFileForm=uploadFileForm)

@uf_bp.route('/process_upload', methods=['GET'])
def processUpload():
    secure_filename = request.args.get('secure_filename')
    output_file = engine.checkFileType(secure_filename)
    return render_template('result.html', secure_filename=output_file)

@uf_bp.route('/download_result', methods=['GET'])
def downloadResult():
    secure_filename = request.args.get('secure_filename')
    return send_file(os.path.join(os.getcwd(), 'results/{}'.format(secure_filename)),mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', attachment_filename='result.xlsx',as_attachment=True)

app/templates/result.html
{% extends "bootstrap/base.html" %}
{% block title %}Success{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h4> Processed Successfully </h4>
    </div>
    <div class="row">
        <a href="{{url_for('uf_bp.downloadResult', secure_filename=secure_filename)}}" class="btn btn-primary">Download File</a>
    </div>
</div>
{% endblock %}

app/templates/uploadFile.html
{% extends "bootstrap/base.html" %}
{% block title %}Gocchii : Auto MM Processor{% endblock %}

{% block scripts %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <h4 class="input">Select File</h4>
    </div>
    <div class="row">
        <div class="col-md-3">
            <form class="form-group" method="post" enctype="multipart/form-data">
                <div class="col-md-10">
                    {{ uploadFileForm.hidden_tag() }}
                    {{ uploadFileForm.file }}
                </div>

                <div class="col-md-2">
                    <div class="span-1">
                        <input class="input" type="submit" onclick="$('#loading').show();">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div id="loading" style="display:none;"><img src="{{url_for('.static', filename='gif/loading.gif')}}"
                alt="" />Loading!</div>
    </div>
</div>
{% endblock %}